### ISSUE TITLE
Support for Lumen

### ISSUE THREAD

**Issue by sthales** [GrKamil/laravel-telegram-logging#14]
Any possibility of creating a version that supports Lumen?

**Comment by GrKamil** [comment]
I have fixed composer requirements. Now, you can use it with Lumen. 

You need to place the config file config/telegram-logger.php with code from this file: https://github.com/GrKamil/laravel-telegram-logging/blob/master/config/telegram-logger.php

Enable it on: bootstrap/app.php like:
`$app->configure('telegram-logger');`

Also, you need to remember to uncomment `$app->withFacades();` and place config/logging.php file.
