### ISSUE TITLE
Upgrade to support php 8.0

### ISSUE THREAD

**Issue by Eixix** [GrKamil/laravel-telegram-logging#16]
Are there any plans to update accordingly?

**Comment by GrKamil** [comment]
Yes, I will update soon.

**Comment by nessor** [comment]
The composer.json already have php 8.0 as a requirement 

https://github.com/GrKamil/laravel-telegram-logging/blob/01c7cc6004739329aff7099b3d5e9d01d5bdbeaa/composer.json#L11

So is it implemented?

**Comment by GrKamil** [comment]
Yes, you can try

**Comment by nessor** [comment]
Can't try it at the moment. Was more like an little reminder to this issue here :)
