### ISSUE TITLE
Allow config for ignoreEmptyContextAndExtra

### ISSUE THREAD

**Issue by SauravKumal** [GrKamil/laravel-telegram-logging#20]
https://github.com/GrKamil/laravel-telegram-logging/blob/f746dbb2413afdaac7faa9465000e50b33a6b8e3/src/TelegramHandler.php#L98

possible quick solution:
`return new LineFormatter("%message% %context% %extra%\n",null, false, true);`

Or can add them to config for flexibility

**Comment by frknakk** [comment]
I just had the same problem: The logs contain two extra square brackets at the end. So the original log message "The system is down!" is formatted to "The system is down! [] []".

The 4th parameter$ignoreEmptyContextAndExtra of LineFormatter constructor hides empty arrays from formatted output.

**Comment by GrKamil** [comment]
I have fixed as you suggested. If someone want to make PR with flexible values (move the line formatter options to config) it would be great.
