### ISSUE TITLE
possible to implement a custom getDefaultFormatter?

### ISSUE THREAD

**Issue by luisrossi** [grkamil/laravel-telegram-logging#21]
Would it be possible to implement a custom getDefaultFormatter?
I would like to create my log in a specific format and with some user session data.

**Comment by SauravKumal** [comment]
> Would it be possible to implement a custom getDefaultFormatter?
> I would like to create my log in a specific format and with some user session data.

For now you can extend `TelegramHandler` and `TelegramLogger` class and override the `getDefaultFormatter()` function. And point the new `TelegramLogger` class in `config/logging.php->telegram->via` option.

Also I have created a pull request for generating custom view for customized formatting as needed.
