### ISSUE TITLE
How to Notify Only When "Production" Environment?

### ISSUE THREAD

**Issue by urangdev** [grkamil/laravel-telegram-logging#29]
I have both environment staging & production.  How to enable log telergam notif only when production? In staging just want log to file.

**Comment by nguyentranchung** [comment]
Change .env

Local
```
LOG_CHANNEL=stack
LOG_CHANNEL_STACK=single
```

Production
```
LOG_CHANNEL=stack
LOG_CHANNEL_STACK=single,telegram
```
