### ISSUE TITLE
composer doesn't allow to require this package with laravel 5.8

### ISSUE THREAD

**Issue by underwear** [GrKamil/laravel-telegram-logging#4]
Problem 1
    - Installation request for grkamil/laravel-telegram-logging ^0.1.2 -> satisfiable by grkamil/laravel-telegram-logging[0.1.2].
    - Conclusion: remove laravel/framework v5.8.28
    - Conclusion: don't install laravel/framework v5.8.28
    - grkamil/laravel-telegram-logging 0.1.2 requires laravel/framework 5.6.*|5.7.* -> satisfiable by laravel/framework[5.6.x-dev, 5.7.x-dev].
    - Can only install one of: laravel/framework[5.6.x-dev, v5.8.28].
    - Can only install one of: laravel/framework[5.7.x-dev, v5.8.28].
    - Installation request for laravel/framework (locked at v5.8.28, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.28].

**Comment by GrKamil** [comment]
Fixed, pls update the package version

**Comment by GrKamil** [comment]
Latest version: https://github.com/GrKamil/laravel-telegram-logging/releases/tag/v1.0.1

**Comment by underwear** [comment]
thanks a lot!
